#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

export GET_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

mkdir -p ~/.local/share/nvim/site/autoload
curl --insecure -fLo ~/.local/share/nvim/site/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
